# Generated by Django 4.2.4 on 2025-08-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(default='1234', max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
