# Generated by Django 5.2.3 on 2025-08-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_userregistration_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
