# Generated by Django 5.2.3 on 2025-08-14 08:56

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_userregistration_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=50, validators=[registration.models.validate_password]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
