# Generated by Django 5.2.3 on 2025-08-14 11:23

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_userregistration_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=128, validators=[registration.models.validate_password]),
        ),
    ]
