# Generated by Django 5.2.3 on 2025-08-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_userregistration_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
